### ISSUE TITLE
Error resolving db (~> 0.7.0, ~> 0.8.0)

### ISSUE THREAD

**Issue by lebogan** [amberframework/micrate#48]
How do I update micrate (and granite) to use crystal-db 0.8.0? I'm using Crystal 0.32.1.
shard.yml snippet:

```
dependencies:
  pg:
    github: will/crystal-pg
  sqlite3:
    github: crystal-lang/crystal-sqlite3
  mysql:
    github: crystal-lang/crystal-mysql
  granite:
    github: amberframework/granite

```
Thanks in advance.
